### ISSUE TITLE
Installer

### ISSUE THREAD

**Issue by DPeterK** [informatics-lab/tiledb_netcdf#44]
We should have a better install process than 'copy the directory to your CWD'. At minimum, a `setup.py` would be good.

**Comment by grumbling-tom** [comment]
Hi @DPeterK , are you looking for contributors at the moment? I'd be really keen for an easy-to-use TileDB writer, but have had trouble getting this package installed. Happy to help out, if needed!

**Comment by DPeterK** [comment]
Hi @grumbling-tom! I'm very happy to receive contributions to this repo - thanks for offering!

The obvious Python package installer options, in order of (potentially) increasing complexity and (definitely) increasing value are:
* a `setup.py`
* installable with pip (follows on from a `setup.py`, if memory serves), and
* installable with conda

If you're able to help out with any of these that would be great.

**Comment by grumbling-tom** [comment]
Fantastic - I'll start with `setup.py` and go from there!

**Comment by grumbling-tom** [comment]
Looks like we can close this issue now, @DPeterK :tada:

**Comment by DPeterK** [comment]
@grumbling-tom indeed so! Thanks again 🙂
